name: Download Proto Files and Install Protoc
description: Downloads required proto files and install protoc

inputs:
  cdn:
    description: Base CDN URL
    required: true
  token:
    description: GitHub token for authentication
    required: true

runs:
  using: "composite"
  steps:
    - name: Create proto folder
      run: mkdir -p proto
      shell: bash

    - name: Download packetIds.json
      run: curl -sSL "${{ inputs.cdn }}/packetIds.json" -o proto/packetIds.json
      shell: bash

    - name: Download protos.proto
      run: curl -sSL "${{ inputs.cdn }}/protos.proto" -o proto/protos.proto
      shell: bash
    
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ inputs.token }}
