name: Download Proto Files and Install Protoc
description: Downloads required proto files and install protoc

inputs:
  cdn:
    description: Base CDN URL
    required: true

runs:
  using: "composite"
  steps:
    - name: Create proto folder
      run: mkdir -p proto
      shell: bash

    - name: Download packetIds.json
      run: curl -sSL "$CDN/packetIds.json" -o proto/packetIds.json
      shell: bash
      env:
        CDN: ${{ inputs.cdn }}

    - name: Download protos.proto
      run: curl -sSL "$CDN/protos.proto" -o proto/protos.proto
      shell: bash
      env:
        CDN: ${{ inputs.cdn }}
    
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
