name: Check Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PROTOS_CDN: ${{ secrets.PROTOS_CDN }}
    steps:
      - uses: actions/checkout@v4

      - name: Download proto files
        run: |
          curl -sSL "$PROTOS_CDN/packetIds.json" -o proto/packetIds.json
          curl -sSL "$PROTOS_CDN/protos.proto" -o proto/protos.proto

      - name: Setup Rust
        run: |
          rustup update nightly
          rustup default nightly

      - name: Run cargo check
        run: cargo check --all --verbose
