name: Check Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PROTOS_CDN: ${{ secrets.PROTOS_CDN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup update nightly
          rustup default nightly

      - name: Download Proto Files and Install Protoc
        uses: ./.github/actions/protos
        with:
          cdn: ${{ env.PROTOS_CDN }}

      - name: Run cargo check
        run: cargo check --all --verbose
